server:
  port: 8081
  # 因为不实用servlet， 所以context-path无效
#  servlet:
#    context-path: /webflux

spring:
  datasource:
    url: jdbc:h2:D:\Data\h2\test1
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: update

  h2:
    console.enabled: true
    console.path: /console
    console:
      settings:
        trace: false
        web-allow-others: false
