server:
  port: 9401
  servlet:
    context-path: /rabbitmq

spring:
  rabbitmq:
    addresses: 10.43.7.72
    host: 5672
    username: test
    password: test
    virtual-host: /
    publisher-confirms: true  # 消息的确认
    publisher-returns: true  # 支持发布返回
    listener:
      simple:
#        acknowledge-mode: manual  #采用手动应答
        concurrency: 1        #并发消费者数量
        max-concurrency: 20   #指定最大的消费者数量
        prefetch: 5
        retry:
          enabled: true   #是否支持重试
