server:
  port: 11000
  servlet:
    context-path: /mingblog

logging:
  config: classpath:log4j2-prod.xml

spring:
  profiles: prod
  datasource:
    # 主库数据源
#    url: jdbc:mysql://106.52.88.16:3306/mybatis1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    url: jdbc:mysql://06.52.88.16:3306/mybatis1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: jiang@123
    driverClassName: com.mysql.cj.jdbc.Driver
    # 初始连接数
    initial-size: 10
    # 最大连接池数量
    max-active: 100
    # 最小连接池数量
    min-idle: 10
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    stat-view-servlet:
      enabled: true
      url-pattern: /monitor/druid/*
    filter:
      stat:
        db-type: mysql
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true
      log4j:
        enabled: true
        statement-create-after-log-enabled: false
        statement-close-after-log-enabled: false
        result-set-open-after-log-enabled: false
        result-set-close-after-log-enabled: false
#logging:
#  config: classpath:log4j2-boot-yulaide.xml