server:
  port: 9001
  servlet:
    context-path: /cache

spring:
  cache:
    type: CAFFEINE
#    cache-names: test1,test2,test3
#    caffeine:
#      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=15s #,refreshAfterWrite=7s  # expireAfterWrite=5s