server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:D:\Data\h2
    driver-class-name: org.h2.Driver
    username: user
    password: 123456

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: update

  h2:
    console.enabled: true
    console.path: /console
    console:
      settings:
        trace: false
        web-allow-others: false
