server:
  port: 9001
  servlet:
    context-path: /permission

jwt:
  config:
    header: auth
    secret: templage20200331
    #token有效期一天
    expiration: 86400
    tokenHead: "Bearer "

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-one?characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update

  security:
    user:
      name: admin
      password: admin
