server:
  port: 10000
  servlet:
    context-path: /mingblog/mybatis

spring:
  datasource:
    filters: stat,wall,log4j
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://106.52.88.16:3306/mybatis1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: jiang@123
      configuration:
        maxmum-pool-size: 10
    secondary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://106.52.88.16:3306/mybatis2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: jiang@123
      configuration:
        maxmum-pool-size: 10